name: Blazor CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dj-app-ui dependencies
        run: dotnet restore dj-app-ui/Dj.csproj

      - name: Build dj-app-ui
        run: dotnet build -c Release --no-restore dj-app-ui/Dj.csproj

      - name: Restore DjTests dependencies
        run: dotnet restore DjTests/DjTests.csproj

      - name: Build DjTests
        run: dotnet build -c Release --no-restore DjTests/DjTests.csproj

      - name: Run tests
        run: dotnet test -c Release --no-build DjTests/DjTests.csproj
