name: Blazor CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore DjTests/DjTests.csproj

      - name: Build the solution
        run: dotnet build -c Release --no-restore DjTests/DjTests.csproj DjApp/DjApp.csproj

      - name: Run tests
        run: dotnet test -c Release --no-build DjTests/DjTests.csproj
